language: go
go:
  - 1.4
install:
  - go get github.com/spf13/hugo
script: make
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: rtlong.com
    local_dir: public
    skip_cleanup: true
    upload-dir: staging
    on:
      repo: rtlong/rtlong.com
      branch: master
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: rtlong.com
    local_dir: public
    skip_cleanup: true
    upload-dir: production
    on:
      repo: rtlong/rtlong.com
      branch: production
