
### BEGIN All built-in config variables ###
# archetypeDir =                "archetypes"
# hostname (and path) to the root, e.g. http://spf13.com/
baseURL =                     "https://rtlong.com"
# include content marked as draft
buildDrafts =                 false
# include content with publishdate in the future
buildFuture =                 false
# include content already expired
buildExpired =                false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
# relativeURLs =                false
# canonifyURLs =                false
# config file (default is path/config.yaml|json|toml)
# config =                     "config.toml"
# contentDir =                  "content"
# dataDir =                     "data"
# defaultLayout =               "post"
# Missing translations will default to this content language
# defaultContentLanguage =      "en"
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
# defaultContentLanguageInSubdir =  false
# disableLiveReload =           false
# Do not build RSS files
# disableRSS =                  false
# Do not build Sitemap file
# disableSitemap =              false
disqusShortname = "rtlong"
# Enable GitInfo feature
enableGitInfo =               true
# Build robots.txt file
enableRobotsTXT =             true
# Do not render 404 page
# disable404 =                  false
# Do not inject generator meta tag on homepage
# disableHugoGeneratorInject =  false
# Allows you to disable all page types and will render nothing related to 'kind';
# values = "page", "home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"
# disableKinds = []
# Do not make the url/path to lowercase
# disablePathToLower =          false
# Enable Emoji emoticons support for page content; see emoji-cheat-sheet.com
# enableEmoji =                 false
# Show a placeholder instead of the default value or an empty string if a translation is missing
# enableMissingTranslationPlaceholders = false
# footnoteAnchorPrefix =        ""
# footnoteReturnLinkContents =  ""
# google analytics tracking id
# googleAnalytics =             ""
# if true, auto-detect Chinese/Japanese/Korean Languages in the content. (.Summary and .WordCount can work properly in CJKLanguage)
# hasCJKLanguage =              false
# languageCode =                ""
# the length of text to show in a .Summary
# summaryLength =              70
# layoutDir =                   "layouts"
# Enable Logging
# log =                         false
# Log File path (if set, logging enabled automatically)
# logFile =
# maximum number of items in the RSS feed
# rssLimit =                    15
# "toml","yaml", or "json"
# metaDataFormat =              "toml"
# newContentEditor =            ""
# Don't sync permission mode of files
# noChmod =                     false
# Don't sync modification time of files
# noTimes =                     false
# Pagination
# paginate =                    10
# paginatePath =                "page"
# See "content-management/permalinks"
# permalinks =
# Pluralize titles in lists using inflect
# pluralizeListTitles =         true
# Preserve special characters in taxonomy names ("Gérard Depardieu" vs "Gerard Depardieu")
# preserveTaxonomyNames =       false
# filesystem path to write files to
# publishDir =                  "public"
# enables syntax guessing for code fences without specified language
# pygmentsCodeFencesGuessSyntax = false
# color-codes for highlighting derived from this style
# pygmentsStyle =               "monokai"
# true: use pygments-css or false: color-codes directly
# pygmentsUseClasses =          false
# see "Section Menu for Lazy Bloggers", /templates/menu-templates for more info
# SectionPagesMenu =
# default sitemap configuration map
# sitemap =
# filesystem path to read static files relative from
# staticDir =                   "static"
# display memory and timing of different steps of the program
# stepAnalysis =                false
# theme to use (located by default in /themes/THEMENAME/)
# themesDir =                   "themes"
theme =                       ""
title =                       "RTLong"
# if true, use /filename.html instead of /filename/
uglyURLs =                    false
# verbose output
verbose =                     false
# verbose logging
verboseLog =                  false
# watch filesystem for changes and recreate as needed
# watch =                       true

[taxonomies]
tag = "tags"
category = "category"

### END all built-in variables ###

[author]
main = "Ryan Taylor Long"

[params]
avatarURL = "https://gravatar.com/avatar/053e38be1bd8b18bf8b1c26e11a797ff?s=256"
bg_scroll = "off"
copyright = "2018 Ryan Taylor Long"
email = "hello@rtlong.com"
name = "Ryan Long"
resume_version = "standard"
logo = "fa-paper-plane"

about = "Software Engineer - Digital Nomad"
bio = "Software Engineer - Digital Nomad"
siteDescription = "Software Engineer - Digital Nomad"
description = "Software Engineer - Digital Nomad"

[params.header]
title = "Ryan Long"
logoImageURL = "signature.svg"
shortBio = "Software Engineer. Digital Nomad."

[[params.social]]
medium = "Github"
icon = "github"
link = "https://github.com/rtlong"

[[params.social]]
medium = "LinkedIn"
icon = "linkedin"
link = "https://www.linkedin.com/in/rtlong"

[[params.social]]
medium = "Instagram"
icon = "instagram"
link = "https://www.instagram.com/_rtlong/"

[[params.social]]
medium = "Email"
icon = "envelope"
link = "mailto:hello@rtlong.com"