---
baseURL: "/"
languageCode: "en-us"
log: true # Enable Logging
metaDataFormat: "yaml"
verbose: true # verbose output
verboseLog: true # verbose logging
uglyURLs: true
buildDrafts: true
buildFuture: true

# theme: rtlong
theme: future-imperfect

title: RTLong

author:
  main: Ryan Taylor Long

params:
  name: Ryan Long
  siteDescription: Software Engineer. Digital Nomad.
  email: hello@rtlong.com
  bio: Software Engineer. Digital Nomad.
  avatarURL: https://gravatar.com/avatar/053e38be1bd8b18bf8b1c26e11a797ff?s=256

  header:
    title: Ryan Long
    logoImageURL: signature.svg
    shortBio: "Software Engineer. Digital Nomad."

  instagram:
    clientId: 7f680a7143eb47d7b7af71ddf5231e03
    accessToken: 417765262.7f680a7.4843caf7cc83481b89c5da6de97040e5 # only granted access to the above application and only very basic permissions -- no risk in having it here
    userId: 417765262

SectionPagesMenu: main

preserveTaxonomyNames: true

# taxonomies: {}
# permalinks: {}
