baseURL = "https://rtlong.com" # hostname (and path) to the root, e.g. http://spf13.com/
buildDrafts = true # include content marked as draft
buildFuture = false # include content with publishdate in the future
buildExpired = false # include content already expired
relativeURLs = false # enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
canonifyURLs = false
debug = true
disableLiveReload = false
disableRSS = false # Do not build RSS files
disableSitemap = false # Do not build Sitemap file
disqusShortname = "rtlong"
enableGitInfo = true # Enable GitInfo feature
enableRobotsTXT = true # Build robots.txt file
disable404 = false # Do not render 404 page
disableHugoGeneratorInject = false # Do not inject generator meta tag on homepage
disableKinds = [] # Allows you to disable all page types and will render nothing related to 'kind'; values = "page", "home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"
disablePathToLower = false # Do not make the url/path to lowercase
enableEmoji = true # Enable Emoji emoticons support for page content; see emoji-cheat-sheet.com
enableMissingTranslationPlaceholders = false # Show a placeholder instead of the default value or an empty string if a translation is missing
googleAnalytics = "" # google analytics tracking id
metaDataFormat = "yaml" # "toml","yaml", or "json"
staticDir = ["static", "asset-bundles"]
# theme = "rtlong"
title = "RTLong"
uglyURLs = false # if true, use /filename.html instead of /filename/
verbose = true # verbose output
verboseLog = true # verbose logging
watch = true # watch filesystem for changes and recreate as needed
# End built-ins
copyright = "2015 Ryan Taylor Long"

[taxonomies]
tag = "tags"
category = "category"

[permalinks]

[author]
main = "Ryan Taylor Long"

[params]
avatarURL = "https://gravatar.com/avatar/053e38be1bd8b18bf8b1c26e11a797ff?s=256"
email = "hello@rtlong.com"
name = "Ryan Long"
resume_version = "standard"
logoIcon = "fa-paper-plane"
tagline = "Software Engineer - Digital Nomad"

[params.header]
title = "Ryan Long"
logoImageURL = "signature.svg"
shortBio = "Software Engineer. Digital Nomad."

[[params.social]]
medium = "Github"
icon = "github"
link = "https://github.com/rtlong"

[[params.social]]
medium = "LinkedIn"
icon = "linkedin"
link = "https://www.linkedin.com/in/rtlong"

[[params.social]]
medium = "Instagram"
icon = "instagram"
link = "https://www.instagram.com/_rtlong/"

[[params.social]]
medium = "Email"
icon = "envelope"
link = "mailto:hello@rtlong.com"

# [[menu.main]]
# name = "Contact"
# url = "mailto:hello@rtlong.com"
# weight = 200

[[menu.main]]
name = "Github"
url = "https://github.com/rtlong"
weight = 0

[[menu.main]]
name = "Resume"
url = "/resumes/standard/"
identifier = "resumes"
weight = 0