---
baseURL: "/"
languageCode: "en-us"
log: true # Enable Logging
metaDataFormat: "yaml"
verbose: true # verbose output
verboseLog: true # verbose logging
uglyURLs: true
buildDrafts: true
buildFuture: true

title: RTLong
author:
  main: Ryan Taylor Long

params:
  name: Ryan Long
  siteDescription: Software Engineer. Digital Nomad.
  email: hello@rtlong.com
  bio: Software Engineer. Digital Nomad.
  avatarURL: https://gravatar.com/avatar/053e38be1bd8b18bf8b1c26e11a797ff?s=256

  header:
    title: Ryan Long
    logoImageURL: signature.svg
    shortBio: "Software Engineer. Digital Nomad."

# taxonomies: {}
# permalinks: {}