---
version: '2'
services:
  webpack:
    build:
      context: .
      dockerfile: Dockerfile.webpack
    command: webpack
    volumes:
      - '.:/app'
  hugo:
    build:
      context: .
      dockerfile: Dockerfile.hugo
    volumes:
      - '.:/app'

  nginx:
    image: nginx
    volumes:
      - './public:/usr/share/nginx/html:ro'
    ports:
      - 80