#!/bin/bash

set -euo pipefail

docker_env="$(docker-machine env $DOCKER_MACHINE_NAME | grep -vE '^#' | tr "\n" ' ')"

tmux split-window -h bash -c "${docker_env} && forego start"

sleep 4 # wait for build to complete
./script/dev-open
