#!/bin/bash

set -euo pipefail

# This is used instead of hugo's built-in watch because the filesystem events that hugo watches for are not triggered on the docker-machine VM when the edits happen in OSX (this is not specific to Hugo and is caused by a shortcoming of VirtualBox).

trap 'exit 1' SIGINT

printf '\033]2;%s\033\\' "hugo-watch"

# run immediately
make hugo

# then wait until any of these files/dirs has a change
fswatch -1 content layouts config.yml tmp/webpack-assets.json static data

# and run itself over again
exec $0 "$@"
