#!/bin/bash

set -euo pipefail

# This is used instead of hugo's built-in watch because the filesystem events that hugo watches for are not triggered on the docker-machine VM when the edits happen in OSX (this is not specific to Hugo and is caused by a shortcoming of VirtualBox).

trap 'exit 1' SIGINT

printf '\033]2;%s\033\\' "hugo-watch"

msg() {
	echo $1
}

if command -v terminal-notifier >/dev/null 2>&1 && command -v reattach-to-user-namespace >/dev/null 2>&1; then
		echo 'msg() redefined with terminal-notifier'
		msg() {
			local message="$1"; shift

			echo "$message"
			reattach-to-user-namespace terminal-notifier -title 'rtlong.com' -message "${message}"
		}
fi

# run immediately
make hugo && msg 'build succeeded' || msg 'build failed'

# then wait until any of these files/dirs has a change
fswatch -1 content/ layouts/ config.yml tmp/ static/ data/ themes/ script/hugo-watch

# and run itself over again
exec $0 "$@"
