#!/bin/bash

set -euo pipefail

# This is used instead of webpack's built-in watch because the filesystem events that webpack watches for are not triggered on the docker-machine VM when the edits happen in OSX (this is not specific to Webpack and is caused by a shortcoming of VirtualBox).

trap 'exit 1' SIGINT

printf '\033]2;%s\033\\' "webpack-watch"

# run immediately
make webpack

# then wait until any of these files/dirs has a change
fswatch -1 styles javascripts

# and run itself over again
exec $0 "$@"
